### ISSUE TITLE
unnecessarily difficult to access metadata

### ISSUE THREAD

**Issue by oeilbott** [chstan/autodiDAQt#4]
At present, the 'comment' metadata (e.g. scan parameters, notes, name) are saved in the same file as the step-by-step log. The comment is typically a few dozen lines long, and the step-by-step log can be millions of lines long. 

It could be good to save these two items in separate files so that one can access the comment metadata of many scans using the standard python .json library (which seems to load entire file) without having to read from gigabytes+ of data from all of the scans.

Simple workaround is to load each file line-by-line until its comment has been fully read.

**Comment by chstan** [comment]
Added `metadata-short.json` in addition to the full metadata record.
